<?php
$sample=$block->getArticles(); //getArticles from the block...
?><table >
 <tr>
    <th>Job role</th>
    <th>place</th>
    <th> Experience</th>
</tr>

<?php foreach ($sample as $data): ?>
    <?php if ($data->getAvailable() == 'Yes'): ?>
<tr>
        <?php $id=$data->getId();?>

<td><?php echo $data->getJob_role(); ?></td>
<td><?php echo $data->getPlace(); ?></td>
<td><?php echo $data->getExperience(); ?>Year</td>
<td>

<a href="<?php echo $this->getUrl('*/*/displaydetail', ['id' => $id]) ?>">View job</a>
</td>
<hr>
</tr>
<?php endif; ?>
<?php endforeach; ?>
</table>