<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Embitel_User::css/custom.css')?>">

<div class="align">
<div class="leftt">
<?php
$model = $block->getData('news_career');
?>
<div style="float:inline;">
<h1><?php echo $model->getTitle(); ?></h1>
<p><b>  Job Role  </b>
<div>
    <?php echo $model->getJob_role(); ?></p>
</div>
<p><b>Experience </b>
<div> <?php echo $model->getExperience(); ?></p>
</div>

<p><b>Job Description </b>
<div>
    <?php echo $model->getJob_description(); ?></p>
</div>
<p><b>Job Responsibility </b>
<div> <?php echo $model->getJob_responsibility(); ?></p></div>
<?php $custId = $this->getRequest()->getParam('id'); ?>

</div>
</div>
<div>