<?php $h=  $this->getRequest()->getFullActionName(); if($h == 'cms_index_index'){?>
<div class="margin_collapsetop"></div>
<div id="ttr_slideshow_inner">
<ul>
<li id="Slide0" class="ttr_slide" data-slideEffect="None">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="None" data-easing="linear" data-slide="None" data-duration="0">
</div>
<div class="ttr_slideshowshape01" data-effect="None" data-begintime="0" data-duration="1" data-easing="linear" data-slide="None">
<div class="html_content"><p style="text-align:Center; display:block; line-height:5.41em;"><span style="font-family:'STIX Two Text','Arial';font-size:4.643em;color:rgba(255,255,255,1);">Best Magazine Online Store</span></p></div>
</div>
</div>
</li>
<li id="Slide1" class="ttr_slide" data-slideEffect="Fade">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="None" data-easing="linear" data-slide="None" data-duration="0">
</div>
</div>
</li>
</ul>
</div>
<div class="ttr_slideshow_in">
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container">
</div>
<div id="nav"></div>
<div class="ttr_slideshow_logo">
</div>
</div>
</div>
<?php } ?>
